Support convTranspose
Idein/onnion pull request #201
Opened 2023-07-18 06:33 UTC by eguchi1904

2023-07-18 07:59 UTC, eguchi1904 commented on runtime/tests/utils.py
> +    return helper.np_dtype_to_tensor_dtype(dtype)
using ` mapping.NP_TYPE_TO_TENSOR_TYPE[dtype]` cause following deperecation warning.
```
 DeprecationWarning: `mapping.NP_TYPE_TO_TENSOR_TYPE` is now deprecated and will be removed in a future release.To silence this warning, please use `helper.np_dtype_to_tensor_dtype` instead.
    return mapping.NP_TYPE_TO_TENSOR_TYPE[dtype]
```

2023-07-19 06:50 UTC, ishiy1993 requested changes
Add tests which use `b`.

2023-07-19 06:50 UTC, ishiy1993 commented on runtime/README.md
> +  - `auto_pad` should be `NONE` or `"NOTSET"`
```suggestion
  - `auto_pad` should be `"NOTSET"` (default value)
```

2023-07-19 06:50 UTC, ishiy1993 commented on runtime/onnion_runtime/convtranspose.py
> +        self.group = kwargs.get("group", None)
```suggestion
        self.group = kwargs.get("group", 1)
```

2023-07-19 07:27 UTC, ishiy1993 approved these changes
LGTM

2023-07-19 07:27 UTC, eguchi1904 commented
:pray:

2023-07-19 07:27 UTC, merged